# Generated by Django 4.2.3 on 2023-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_user_age_alter_users_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(0, '남성'), (1, '여성')], default=0),
        ),
    ]
