# Generated by Django 4.2.3 on 2023-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_users_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
